### ISSUE TITLE
Jim's comments 2/13/2017

### ISSUE THREAD

**Issue by tyleransom** [ModUDuke/causalinference#2]
@bentleygcoffey Here's a summary of what we discussed today; feel free to chime in.
### General Discussion:
- Do we have the general pacing correct? (ratio of multiple choice to coding exercises; among multiple choice do we have a good ratio of reading comprehension to critical thinking?)
- What about simplifying the exercises? Right now there's like 6 things that people need to remember when they do an exercise. 
    * question about if we need to randomize the answers eventually or if we should not worry about this
    * re-work the OHIE coding problem to provide more context; simplify the set of tasks in the problem
        - for example, don't word questions so authoritatively; give the user some free reign to arrive at the conclusion on his/her own.
        - More wording like "the CEO asks you to figure out X" ... 
- Figure out how to optimize the "cognitive flow"
    * Do some coding exercises early, but also do a lot of MC exercises. Want to test lots of "easy" stuff at the beginning, and gradually get more complex. Can do some repeat testing to drive home key principles.
- Also keep in mind Duke audiences (not just pandering completely to eBay for this project)
    * e.g. bootcamps that could use what we are doing
        - Sociology (entrance bootcamp)
        - Economics (geared towards rising 2nd year students)
- It would be nice to find an R user who doesn't know this stuff who could serve as a beta tester for us.

### Specific content points:
- Make sure we drive home the set of things that can go wrong in experiments (re-watch Matt's videos to generate this list)
    * test these in various ways (Multiple choice, coding, etc.)
    * Examples of this list:
        - Balance (are the treatment and control groups actually equal on observables?)
        - Experimental non-compliance
        - Survey non-response
        - External validity
        - Spillovers (SUTVA)
        - Bounds analysis
    * Test the above in "juicy multiple choice questions"

### Goal:
- Get the draft of the course to eBay by Monday, Feb. 20, 2017.

### To do items
- @ModUDuke (Jim):
    * Talk to Jimmy R.
    * Upload wording suggested changes to markdown files (directly in GitHub)
    * Continue working with @bentleygcoffey on videos
- @BrianAronson: 
    * Find out if DataCamp requires "burner" accounts or if we can share the course with anyone who has the link
- @bentleygcoffey: 
    * Read through this and provide comments.
    * Review your videos and discuss with Jim
- @tyleransom: 
    * Incorporate others' feedback as required
- @AC-SSRI (Alexandra):
    * Start thinking about how to set up bootcamps on this course with other departments

**Comment by tyleransom** [comment]
@bentleygcoffey says:
- We're fine, pacing-wise. We probably shouldn't simplify the exercises too much because we're dealing with Silicon Valley types
- Clean up the error feedback to say "This is tempting, but that's not the right answer because ..." There shouldn't be any "gimmes"
- Sent message to Jim about videos.
- Will pass this around to my undergraduates who are taking my intro to econometrics class.

**Comment by BrianAronson** [comment]
Nice notes! On it

**Comment by ModUDuke** [comment]
Hey Brian, I was about to do some wording edits—will it mess things up if we’re both in there at the same time?  I figure it will, and I have some other stuff I can do if you want to do github stuff right now.  I’m happy to let you code in there for now—that’s more important right now, but gimme a heads up if you know how long you’ll be.

Jim


--
James Speckart
Program Manager for Instructional Design
Social Sciences Research Institute at Duke University
Website: https://modu.ssri.duke.edu

**Comment by BrianAronson** [comment]
Hey Jim, I'm learning that GitHub is really good at dealing with multiple versions and allowing for multiple people to edit a document at the same time. Feel free to work on it as I do - I'll make sure to merge our changes.

**Comment by ModUDuke** [comment]
Cool. Already doing it.


--
James Speckart
Program Manager for Instructional Design
Social Sciences Research Institute at Duke University
Website: https://modu.ssri.duke.edu

**Comment by tyleransom** [comment]
@BrianAronson @ModUDuke @bentleygcoffey @AC-SSRI I finished the re-write of the Multiple Choice question titles, and I believe that the questions are better worded, with more informative explanations for each of the answers.

DataCamp appears to be building as expected, but there still may be a problem of missing videos. Let me know if you need my help on this.

**Comment by AC-SSRI** [comment]
Thank you!  AC


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^

  Alexandra Cooper
  Associate Director for Research, Education, and Evaluation, Social
Science Research Institute
  Associate Director, Duke Initiative on Survey Methodology
  Box 90989
  Duke University
  Durham, NC  27708-0989
  Phone:  (919)681-3902
  Fax:  (919)681-4299

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^
