### ISSUE TITLE
Practice with eGulf

### ISSUE THREAD

**Issue by tyleransom** [ModUDuke/causalinference#3]
I just did the eGulf t-test of difference in means, and I got the same answer but DataCamp told me it was wrong.

The correct answer was:
```
t.test(eGulf$Final_Sales_Price[eGulf$Seller_Opted_Into_Treatment==1],eGulf$Final_Sales_Price[eGulf$Seller_Opted_Into_Treatment==0])
```
whereas I submitted
```
t.test(eGulf[eGulf$Seller_Opted_Into_Treatment==1,c("Final_Sales_Price")],eGulf[eGulf$Seller_Opted_Into_Treatment==0,c("Final_Sales_Price")])
```

**Comment by BrianAronson** [comment]
Odd. I tested the problem and you're right. I'm not sure what's wrong with this one. My guess is that t.test objects are order dependent. In R, t.test(a,b) is probably not equivalent to t.test(b,a); they just produce the same results. If that's the case, I'll have to fix most of the t.test problems. I'll dig into this.

**Comment by tyleransom** [comment]
Notice that the columns are ordered the same way in my example; it's simply a difference in syntax with how the data are subset.

I don't think this is a big issue right now; I added it on the issue tracker simply so we wouldn't forget about it later.

**Comment by BrianAronson** [comment]
True, subsetting seems to be a problem too. However, I just tested a case with my theory and it's also broken. The following doesn't yield a correct solution:

Solution1<-t.test(eGulf$Final_Sales_Price[eGulf$Seller_Opted_Into_Treatment==0],eGulf$Final_Sales_Price[eGulf$Seller_Opted_Into_Treatment==1])

**Comment by bentleygcoffey** [comment]
The good news is that r is open source. If you just type t.test then it will dump the c code for you to see what it's doing. In general, when you pass arguments to a function in r, you can explicitly identify what parameters you are passing or you can let r infer it from order and data type. Hence, the order of arguments can matter. In general, the safest way is to pass anyone is to do it explicitly... Bigger picture, I continue to believe that we should just show them what our answer was (including the source code of how we got it) and let them (i.e. the user) do the comparison to their own work using their own brain...

**Comment by bentleygcoffey** [comment]
* Anything, no anyone!!! ;)

**Comment by tyleransom** [comment]
@bentleygcoffey You can edit comments by clicking on the pencil icon in the top right corner of the comment box. 👍

**Comment by BrianAronson** [comment]
I like Bentley's suggestion, but probably for the wrong reason (it allows us to get around this thorny problem). I'm interested in what others think about accepting all answers. My only worry is that people might end up just copying and pasting all of our answers without trying to code things themselves. Maybe we could have a mix questions that accept any solution, and ones that only accept a narrow range of solutions.

**Comment by bentleygcoffey** [comment]
Yeah, there is certainly a risk that some people may just copy & paste our answers to cheat the system and put on the appear that they have done everything right. Like we talked about in a recent meeting, there are other ways that they could cheat as well. If eBay will accept it, then I'd prefer to say that this is just eBay's problem (if they care). We can hope that they wouldn't hire people who would cheat on this sort of thing because they'd just be cheating themselves out of some useful knowledge... What do others think?

**Comment by tyleransom** [comment]
Another option would be to restrict the answer set. This won't work for all problems, but for the one in question, we should ask the user to return a p-value or a t-stat rather than the entire t.test output. This should be invariant to the ordering or subsetting, and all that's required is to add `$p.value` or the like.
